// <auto-generated />
using System;
using Desafio_POO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio_POO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019004121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Desafio_POO.Models.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InquilinoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoImovel")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InquilinoId");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("Imoveis");

                    b.HasDiscriminator<string>("TipoImovel").HasValue("Imovel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Desafio_POO.Models.Inquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inquilinos");
                });

            modelBuilder.Entity("Desafio_POO.Models.Proprietario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proprietarios");
                });

            modelBuilder.Entity("Desafio_POO.Models.Apartamento", b =>
                {
                    b.HasBaseType("Desafio_POO.Models.Imovel");

                    b.Property<int>("NumeroApartamento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorCondominio")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("APARTAMENTO");
                });

            modelBuilder.Entity("Desafio_POO.Models.Casa", b =>
                {
                    b.HasBaseType("Desafio_POO.Models.Imovel");

                    b.HasDiscriminator().HasValue("CASA");
                });

            modelBuilder.Entity("Desafio_POO.Models.Imovel", b =>
                {
                    b.HasOne("Desafio_POO.Models.Inquilino", "Inquilino")
                        .WithMany("Imoveis")
                        .HasForeignKey("InquilinoId");

                    b.HasOne("Desafio_POO.Models.Proprietario", "Proprietario")
                        .WithMany("Imoveis")
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquilino");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("Desafio_POO.Models.Inquilino", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("Desafio_POO.Models.Proprietario", b =>
                {
                    b.Navigation("Imoveis");
                });
#pragma warning restore 612, 618
        }
    }
}
